[build]
  command = "JEKYLL_ENV=production jekyll build"
  publish = "_site/"

[[redirects]]
  from = "https://tech-talk-blog.ml/infrastructure/2018/04/16/mac%E3%81%AEnode-js%E3%82%92nodebrew%E3%81%A7%E7%AE%A1%E7%90%86%E3%81%99%E3%82%8B.html"
  to = "https://blog.nakamu.life/posts/mac-node-js-nodebrew"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/04/11/gemfile%E3%81%A7github%E3%81%AE%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95.html"
  to = "https://blog.nakamu.life/posts/gemfile-github"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/03/17/%E4%BB%8A%E6%9B%B4%E6%94%B9%E3%82%81%E3%81%A6-ruby-on-rails%E3%81%AE%E9%96%8B%E7%99%BA%E3%82%92%E8%A1%8C%E3%81%86-part12.html"
  to = "https://blog.nakamu.life/posts/ruby-on-rails-xml"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/03/05/rails-cron%E3%81%A7%E3%83%90%E3%83%83%E3%83%81%E3%82%92%E9%96%8B%E7%99%BA%E3%81%99%E3%82%8B%E3%81%AA%E3%82%89-whenever.html"
  to = "https://blog.nakamu.life/posts/rails-cron-whenever"
  status = 301