[build]
  command = "JEKYLL_ENV=production jekyll build"
  publish = "_site/"

[[redirects]]
  from = "https://tech-talk-blog.ml/about/"
  to = "https://nakamu.life/"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/other/2018/02/02/%E6%8A%80%E8%A1%93%E3%83%96%E3%83%AD%E3%82%B0%E3%81%AF%E3%81%98%E3%82%81%E3%81%BE%E3%81%97%E3%81%9F.html"
  to = "https://blog.nakamu.life/posts/start-blog"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/infrastructure/2018/04/16/mac%E3%81%AEnode-js%E3%82%92nodebrew%E3%81%A7%E7%AE%A1%E7%90%86%E3%81%99%E3%82%8B.html"
  to = "https://blog.nakamu.life/posts/mac-node-js-nodebrew"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/04/11/gemfile%E3%81%A7github%E3%81%AE%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95.html"
  to = "https://blog.nakamu.life/posts/gemfile-github"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/03/17/%E4%BB%8A%E6%9B%B4%E6%94%B9%E3%82%81%E3%81%A6-ruby-on-rails%E3%81%AE%E9%96%8B%E7%99%BA%E3%82%92%E8%A1%8C%E3%81%86-part12.html"
  to = "https://blog.nakamu.life/posts/ruby-on-rails-xml"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/03/05/rails-cron%E3%81%A7%E3%83%90%E3%83%83%E3%83%81%E3%82%92%E9%96%8B%E7%99%BA%E3%81%99%E3%82%8B%E3%81%AA%E3%82%89-whenever.html"
  to = "https://blog.nakamu.life/posts/rails-cron-whenever"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/03/17/nuxt-js%E3%81%AE%E5%9B%BD%E9%9A%9B%E5%8C%96-i18n-%E5%AF%BE%E5%BF%9C.html"
  to = "https://blog.nakamu.life/posts/nuxt-js-i18n"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/03/15/vue%E3%81%AEcss%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0%E3%83%AF%E3%83%BC%E3%82%AF-vuetify-%E3%82%92%E5%88%A9%E7%94%A8%E3%81%97%E3%81%A6nuxt-js%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E4%BD%9C%E3%82%8B.html"
  to = "https://blog.nakamu.life/posts/vue-css-vuetify-nuxt-js"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/design/2018/03/14/css%E3%83%95%E3%83%AC%E3%83%BC%E3%83%A0%E3%83%AF%E3%83%BC%E3%82%AF-bulma-%E3%82%92%E5%88%A9%E7%94%A8%E3%81%99%E3%82%8B%E6%99%82%E3%81%AE%E5%8F%82%E8%80%83url.html"
  to = "https://blog.nakamu.life/posts/css-bulma-url"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/03/13/turbolinks-%E3%82%92npm%E3%81%A7%E5%B0%8E%E5%85%A5%E3%81%99%E3%82%8B.html"
  to = "https://blog.nakamu.life/posts/turbolinks-npm"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/03/13/rails%E3%81%AE%E4%BE%8B%E5%A4%96%E3%82%92slack%E3%81%AB%E9%80%9A%E7%9F%A5%E3%81%99%E3%82%8B-exception_notification.html"
  to = "https://blog.nakamu.life/posts/rails-slack-exception_notification"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/command/2018/02/13/su%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%81%A3%E3%81%A6.html"
  to = "https://blog.nakamu.life/posts/linux-command-su"
  status = 301
  
[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/02/07/ruby%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6tinypng%E3%81%AEdeveloper-api%E3%81%A7%E5%9C%A7%E7%B8%AE%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95.html"
  to = "https://blog.nakamu.life/posts/ruby-tinypng-developer-api"
  status = 301
  
[[redirects]]
  from = "https://tech-talk-blog.ml/blog/2018/02/02/%E6%9C%AC%E3%83%96%E3%83%AD%E3%82%B0%E3%81%AE%E6%A7%8B%E7%AF%89%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6.html"
  to = "https://blog.nakamu.life/posts/building-blog-p1"
  status = 301
  
[[redirects]]
  from = "https://tech-talk-blog.ml/blog/2018/02/03/%E6%9C%AC%E3%83%96%E3%83%AD%E3%82%B0%E3%81%AE%E6%A7%8B%E7%AF%89%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6-part2.html"
  to = "https://blog.nakamu.life/posts/building-blog-p2"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/blog/2018/02/04/%E3%83%96%E3%83%AD%E3%82%B0%E3%81%AE%E6%A7%8B%E7%AF%89%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6-part3.html"
  to = "https://blog.nakamu.life/posts/building-blog-p3"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/blog/2018/02/05/%E3%83%96%E3%83%AD%E3%82%B0%E3%81%AE%E6%A7%8B%E7%AF%89%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6-part4.html"
  to = "https://blog.nakamu.life/posts/building-blog-p4"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/02/08/jekyll%E3%81%A7%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E3%82%92%E4%BD%9C%E6%88%90%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B.html"
  to = "https://blog.nakamu.life/posts/jekyll-custom-plugin"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/infrastructure/2018/02/12/aws%E3%81%AEelasticache%E3%81%A7redis%E3%82%92%E5%88%A9%E7%94%A8%E3%81%99%E3%82%8B.html"
  to = "https://blog.nakamu.life/posts/aws-elasticache-redis"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/03/11/vanilla-js%E3%81%A7form%E3%83%90%E3%83%AA%E3%83%87%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E5%AE%9F%E8%A3%85%E3%81%99%E3%82%8B-bunnyjs.html"
  to = "https://blog.nakamu.life/posts/aws-elasticache-redis"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/programming/2018/02/21/%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%80%E3%83%BC%E3%81%AE%E5%AE%9F%E8%A3%85%E3%81%99%E3%82%8B%E3%81%AA%E3%82%89-flickity.html"
  to = "https://blog.nakamu.life/posts/flickity"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/command/2018/02/12/rsync%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%82%92%E5%AD%A6%E3%82%93%E3%81%A7%E3%81%BF%E3%82%88%E3%81%86.html"
  to = "https://blog.nakamu.life/posts/rsync"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/blog/2018/03/04/jekyll%E3%81%A7%E3%82%A2%E3%83%BC%E3%82%AB%E3%82%A4%E3%83%96%E3%83%9A%E3%83%BC%E3%82%B8%E3%82%92%E4%BD%9C%E3%82%8B.html"
  to = "https://blog.nakamu.life/posts/jekyll-achive"
  status = 301

[[redirects]]
  from = "https://tech-talk-blog.ml/blog/2018/02/19/jekyll%E3%81%A7%E9%96%A2%E9%80%A3%E6%8A%95%E7%A8%BF%E3%82%92%E8%A1%A8%E7%A4%BA.html"
  to = "https://blog.nakamu.life/posts/jekyll-related-post"
  status = 301